### ISSUE TITLE
Continuing to delete presets when there are only 10 left will result in a crash

### ISSUE THREAD

**Issue by XZYawa** [RaydanOMGr/glowingeyes#10]
logs here:

> [latest.log](https://github.com/user-attachments/files/17190785/latest.log)
> [crash-2024-09-30_21.37.35-client.txt](https://github.com/user-attachments/files/17190794/crash-2024-09-30_21.37.35-client.txt)

**Comment by RaydanOMGr** [comment]
This bug is already fixed in an incomplete dev version I'm working on

**Comment by XZYawa** [comment]
> This bug is already fixed in an incomplete dev version I'm working on

Oh okay,sorry to interrupt.
