### ISSUE TITLE
Update mod to 1.20.1 or later versions?

### ISSUE THREAD

**Issue by Ryo-Echidna** [RaydanOMGr/glowingeyes#4]
I found your mod recently because i thought it was pretty cool however i play on 1.20.1 and currently cannot use it. Will it be updated to this version or later versions eventually?

**Comment by RaydanOMGr** [comment]
yes, of course it will be! I've been on a little break from the mod, but I will return to work asap

**Comment by RaydanOMGr** [comment]
Updated the mod
