### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by molocko** [RaydanOMGr/glowingeyes#9]
When is the release date for version 1.21?
I'm really looking forward to it

**Comment by RaydanOMGr** [comment]
There is no release date, it depends on when I have time and how much time I have. Might happen in a week, in a month or in a year, I can't know as I've been busy the past few months.

**Comment by molocko** [comment]
Okay, I'm not rushing you, the main thing is that at least someday the mod is released, it doesn't matter when, in any case I'll wait. GL
